project_name: lorawan-stack

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/v3/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

