// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: lorawan-stack/api/organization.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _organization_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Organization with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Organization) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetIds() == nil {
		return OrganizationValidationError{
			field:  "Ids",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrganizationValidationError{
				field:  "Ids",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrganizationValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrganizationValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetName()) > 50 {
		return OrganizationValidationError{
			field:  "Name",
			reason: "value length must be at most 50 runes",
		}
	}

	if utf8.RuneCountInString(m.GetDescription()) > 2000 {
		return OrganizationValidationError{
			field:  "Description",
			reason: "value length must be at most 2000 runes",
		}
	}

	for key, val := range m.GetAttributes() {
		_ = val

		if utf8.RuneCountInString(key) > 36 {
			return OrganizationValidationError{
				field:  fmt.Sprintf("Attributes[%v]", key),
				reason: "value length must be at most 36 runes",
			}
		}

		if !_Organization_Attributes_Pattern.MatchString(key) {
			return OrganizationValidationError{
				field:  fmt.Sprintf("Attributes[%v]", key),
				reason: "value does not match regex pattern \"^[a-z0-9](?:[-]?[a-z0-9]){2,}$\"",
			}
		}

		// no validation rules for Attributes[key]
	}

	for idx, item := range m.GetContactInfo() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationValidationError{
					field:  fmt.Sprintf("ContactInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// OrganizationValidationError is the validation error returned by
// Organization.Validate if the designated constraints aren't met.
type OrganizationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationValidationError) ErrorName() string { return "OrganizationValidationError" }

// Error satisfies the builtin error interface
func (e OrganizationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganization.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationValidationError{}

var _Organization_Attributes_Pattern = regexp.MustCompile("^[a-z0-9](?:[-]?[a-z0-9]){2,}$")

// Validate checks the field values on Organizations with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Organizations) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetOrganizations() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationsValidationError{
					field:  fmt.Sprintf("Organizations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// OrganizationsValidationError is the validation error returned by
// Organizations.Validate if the designated constraints aren't met.
type OrganizationsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationsValidationError) ErrorName() string { return "OrganizationsValidationError" }

// Error satisfies the builtin error interface
func (e OrganizationsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizations.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationsValidationError{}

// Validate checks the field values on GetOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetOrganizationRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return GetOrganizationRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizationRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetFieldMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizationRequestValidationError{
				field:  "FieldMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetOrganizationRequestValidationError is the validation error returned by
// GetOrganizationRequest.Validate if the designated constraints aren't met.
type GetOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrganizationRequestValidationError) ErrorName() string {
	return "GetOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrganizationRequestValidationError{}

// Validate checks the field values on ListOrganizationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListOrganizationsRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetCollaborator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListOrganizationsRequestValidationError{
				field:  "Collaborator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetFieldMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListOrganizationsRequestValidationError{
				field:  "FieldMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := _ListOrganizationsRequest_Order_InLookup[m.GetOrder()]; !ok {
		return ListOrganizationsRequestValidationError{
			field:  "Order",
			reason: "value must be in list [ organization_id -organization_id name -name created_at -created_at]",
		}
	}

	if m.GetLimit() > 1000 {
		return ListOrganizationsRequestValidationError{
			field:  "Limit",
			reason: "value must be less than or equal to 1000",
		}
	}

	// no validation rules for Page

	return nil
}

// ListOrganizationsRequestValidationError is the validation error returned by
// ListOrganizationsRequest.Validate if the designated constraints aren't met.
type ListOrganizationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationsRequestValidationError) ErrorName() string {
	return "ListOrganizationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationsRequestValidationError{}

var _ListOrganizationsRequest_Order_InLookup = map[string]struct{}{
	"":                 {},
	"organization_id":  {},
	"-organization_id": {},
	"name":             {},
	"-name":            {},
	"created_at":       {},
	"-created_at":      {},
}

// Validate checks the field values on CreateOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateOrganizationRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganization() == nil {
		return CreateOrganizationRequestValidationError{
			field:  "Organization",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrganizationRequestValidationError{
				field:  "Organization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCollaborator() == nil {
		return CreateOrganizationRequestValidationError{
			field:  "Collaborator",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetCollaborator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrganizationRequestValidationError{
				field:  "Collaborator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateOrganizationRequestValidationError is the validation error returned by
// CreateOrganizationRequest.Validate if the designated constraints aren't met.
type CreateOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrganizationRequestValidationError) ErrorName() string {
	return "CreateOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrganizationRequestValidationError{}

// Validate checks the field values on UpdateOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateOrganizationRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganization() == nil {
		return UpdateOrganizationRequestValidationError{
			field:  "Organization",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateOrganizationRequestValidationError{
				field:  "Organization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetFieldMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateOrganizationRequestValidationError{
				field:  "FieldMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateOrganizationRequestValidationError is the validation error returned by
// UpdateOrganizationRequest.Validate if the designated constraints aren't met.
type UpdateOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOrganizationRequestValidationError) ErrorName() string {
	return "UpdateOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOrganizationRequestValidationError{}

// Validate checks the field values on ListOrganizationAPIKeysRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListOrganizationAPIKeysRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return ListOrganizationAPIKeysRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListOrganizationAPIKeysRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetLimit() > 1000 {
		return ListOrganizationAPIKeysRequestValidationError{
			field:  "Limit",
			reason: "value must be less than or equal to 1000",
		}
	}

	// no validation rules for Page

	return nil
}

// ListOrganizationAPIKeysRequestValidationError is the validation error
// returned by ListOrganizationAPIKeysRequest.Validate if the designated
// constraints aren't met.
type ListOrganizationAPIKeysRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationAPIKeysRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationAPIKeysRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationAPIKeysRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationAPIKeysRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationAPIKeysRequestValidationError) ErrorName() string {
	return "ListOrganizationAPIKeysRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationAPIKeysRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationAPIKeysRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationAPIKeysRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationAPIKeysRequestValidationError{}

// Validate checks the field values on GetOrganizationAPIKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetOrganizationAPIKeyRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return GetOrganizationAPIKeyRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizationAPIKeyRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for KeyId

	return nil
}

// GetOrganizationAPIKeyRequestValidationError is the validation error returned
// by GetOrganizationAPIKeyRequest.Validate if the designated constraints
// aren't met.
type GetOrganizationAPIKeyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrganizationAPIKeyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrganizationAPIKeyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrganizationAPIKeyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrganizationAPIKeyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrganizationAPIKeyRequestValidationError) ErrorName() string {
	return "GetOrganizationAPIKeyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrganizationAPIKeyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrganizationAPIKeyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrganizationAPIKeyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrganizationAPIKeyRequestValidationError{}

// Validate checks the field values on CreateOrganizationAPIKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateOrganizationAPIKeyRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return CreateOrganizationAPIKeyRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrganizationAPIKeyRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetName()) > 50 {
		return CreateOrganizationAPIKeyRequestValidationError{
			field:  "Name",
			reason: "value length must be at most 50 runes",
		}
	}

	for idx, item := range m.GetRights() {
		_, _ = idx, item

		if _, ok := Right_name[int32(item)]; !ok {
			return CreateOrganizationAPIKeyRequestValidationError{
				field:  fmt.Sprintf("Rights[%v]", idx),
				reason: "value must be one of the defined enum values",
			}
		}

	}

	return nil
}

// CreateOrganizationAPIKeyRequestValidationError is the validation error
// returned by CreateOrganizationAPIKeyRequest.Validate if the designated
// constraints aren't met.
type CreateOrganizationAPIKeyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrganizationAPIKeyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrganizationAPIKeyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrganizationAPIKeyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrganizationAPIKeyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrganizationAPIKeyRequestValidationError) ErrorName() string {
	return "CreateOrganizationAPIKeyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrganizationAPIKeyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrganizationAPIKeyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrganizationAPIKeyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrganizationAPIKeyRequestValidationError{}

// Validate checks the field values on UpdateOrganizationAPIKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateOrganizationAPIKeyRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return UpdateOrganizationAPIKeyRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateOrganizationAPIKeyRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetApiKey() == nil {
		return UpdateOrganizationAPIKeyRequestValidationError{
			field:  "ApiKey",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetApiKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateOrganizationAPIKeyRequestValidationError{
				field:  "ApiKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateOrganizationAPIKeyRequestValidationError is the validation error
// returned by UpdateOrganizationAPIKeyRequest.Validate if the designated
// constraints aren't met.
type UpdateOrganizationAPIKeyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOrganizationAPIKeyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOrganizationAPIKeyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOrganizationAPIKeyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOrganizationAPIKeyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOrganizationAPIKeyRequestValidationError) ErrorName() string {
	return "UpdateOrganizationAPIKeyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOrganizationAPIKeyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOrganizationAPIKeyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOrganizationAPIKeyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOrganizationAPIKeyRequestValidationError{}

// Validate checks the field values on ListOrganizationCollaboratorsRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, an error is returned.
func (m *ListOrganizationCollaboratorsRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return ListOrganizationCollaboratorsRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListOrganizationCollaboratorsRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetLimit() > 1000 {
		return ListOrganizationCollaboratorsRequestValidationError{
			field:  "Limit",
			reason: "value must be less than or equal to 1000",
		}
	}

	// no validation rules for Page

	return nil
}

// ListOrganizationCollaboratorsRequestValidationError is the validation error
// returned by ListOrganizationCollaboratorsRequest.Validate if the designated
// constraints aren't met.
type ListOrganizationCollaboratorsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationCollaboratorsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationCollaboratorsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationCollaboratorsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationCollaboratorsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationCollaboratorsRequestValidationError) ErrorName() string {
	return "ListOrganizationCollaboratorsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationCollaboratorsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationCollaboratorsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationCollaboratorsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationCollaboratorsRequestValidationError{}

// Validate checks the field values on GetOrganizationCollaboratorRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, an error is returned.
func (m *GetOrganizationCollaboratorRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return GetOrganizationCollaboratorRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizationCollaboratorRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCollaborator() == nil {
		return GetOrganizationCollaboratorRequestValidationError{
			field:  "Collaborator",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetCollaborator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizationCollaboratorRequestValidationError{
				field:  "Collaborator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetOrganizationCollaboratorRequestValidationError is the validation error
// returned by GetOrganizationCollaboratorRequest.Validate if the designated
// constraints aren't met.
type GetOrganizationCollaboratorRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrganizationCollaboratorRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrganizationCollaboratorRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrganizationCollaboratorRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrganizationCollaboratorRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrganizationCollaboratorRequestValidationError) ErrorName() string {
	return "GetOrganizationCollaboratorRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrganizationCollaboratorRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrganizationCollaboratorRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrganizationCollaboratorRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrganizationCollaboratorRequestValidationError{}

// Validate checks the field values on SetOrganizationCollaboratorRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, an error is returned.
func (m *SetOrganizationCollaboratorRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetOrganizationIds() == nil {
		return SetOrganizationCollaboratorRequestValidationError{
			field:  "OrganizationIds",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetOrganizationIds()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetOrganizationCollaboratorRequestValidationError{
				field:  "OrganizationIds",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCollaborator() == nil {
		return SetOrganizationCollaboratorRequestValidationError{
			field:  "Collaborator",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetCollaborator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetOrganizationCollaboratorRequestValidationError{
				field:  "Collaborator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// SetOrganizationCollaboratorRequestValidationError is the validation error
// returned by SetOrganizationCollaboratorRequest.Validate if the designated
// constraints aren't met.
type SetOrganizationCollaboratorRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetOrganizationCollaboratorRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetOrganizationCollaboratorRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetOrganizationCollaboratorRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetOrganizationCollaboratorRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetOrganizationCollaboratorRequestValidationError) ErrorName() string {
	return "SetOrganizationCollaboratorRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetOrganizationCollaboratorRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetOrganizationCollaboratorRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetOrganizationCollaboratorRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetOrganizationCollaboratorRequestValidationError{}
