// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: lorawan-stack/api/picture.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _picture_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Picture with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Picture) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetEmbedded()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PictureValidationError{
				field:  "Embedded",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for key, val := range m.GetSizes() {
		_ = val

		// no validation rules for Sizes[key]

		if _, err := url.Parse(val); err != nil {
			return PictureValidationError{
				field:  fmt.Sprintf("Sizes[%v]", key),
				reason: "value must be a valid URI",
				cause:  err,
			}
		}

	}

	return nil
}

// PictureValidationError is the validation error returned by Picture.Validate
// if the designated constraints aren't met.
type PictureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PictureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PictureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PictureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PictureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PictureValidationError) ErrorName() string { return "PictureValidationError" }

// Error satisfies the builtin error interface
func (e PictureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicture.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PictureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PictureValidationError{}

// Validate checks the field values on Picture_Embedded with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *Picture_Embedded) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for MimeType

	// no validation rules for Data

	return nil
}

// Picture_EmbeddedValidationError is the validation error returned by
// Picture_Embedded.Validate if the designated constraints aren't met.
type Picture_EmbeddedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picture_EmbeddedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picture_EmbeddedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picture_EmbeddedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picture_EmbeddedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picture_EmbeddedValidationError) ErrorName() string { return "Picture_EmbeddedValidationError" }

// Error satisfies the builtin error interface
func (e Picture_EmbeddedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicture_Embedded.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picture_EmbeddedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picture_EmbeddedValidationError{}
